### ISSUE TITLE
v1.5.2 install issue in apex charts

### ISSUE THREAD

**Issue by FozzieUK** [nathanmarlor/foxess_em#117]
Just a quick note to record the few 'minor' issues noticed in the apex charts template after the v1.5.2 update.

In Apex charts template -

Line 35 refers to sensor.load_power_new, this should be sensor.load_power for the majority of systems.

Line 33 appears to perform a transformation changing SoC (%) to usable power but the battery size here needs to be changed to match your system,
   - for example the current line 33 is for a 10.4kwh battery storage    **transform: return ((x / 100) * 10.4) - (0.11 * 10.4)** 
   where the '10.4' is a 10.4kwh battery storage capacity.
   e.g. for an 18.2kwh system line 33 would need to be changed to     **transform: return ((x / 100) * 18.2) - (0.11 * 18.2)**

As the battery SoC is now usable battery but the unit of measurement is left as % and the name could be updated to reflect the transform 'Battery (actual)' and the unit is 'kwh' this needs 2 extra lines inserting after line 29 
[(new)] line 30 -     **name: Battery (actual)**
[(new)] line 31 -     **unit: kwh**

**Comment by nathanmarlor** [comment]
Fixed in #158
