### ISSUE TITLE
Component is not charging my battery

### ISSUE THREAD

**Issue by kevinverelst** [nathanmarlor/foxess_em#148]
## Version of the custom_component

`VERSION = "1.5.0b1"`

## Configuration

```yaml
I'm not sure if I need to give you my overall configuration or just the part concerning foxess_em. If its the latter, where do I find this? 
```

## Describe the bug

I installed this component a week ago and understood that it should auto charge my battery based on the expected solar generation the coming day. 
After a couple of days It seems to do nothing so I tried to use the FoxESS - Energy Management: start_force_charge and FoxESS - Energy Management: stop_force_charge services in an automation to test the fox cloud integration. This works just fine so I'm charging with the automation for a fixed period of time. It's too bad I've been injecting on sunny days when the battery was still full from the nightly charge. 
Is there anything I still need to configure or implement?

Attached are screenshots of the data and configuration
![image](https://user-images.githubusercontent.com/4036085/212675365-7d73d129-39d4-498c-bdc8-9b9220a71fd8.png)
![image](https://user-images.githubusercontent.com/4036085/212675435-fb375697-3141-4dd2-b6ec-6d50e859ff50.png)
![image](https://user-images.githubusercontent.com/4036085/212675478-d9773120-94ef-4051-8ee8-b4716925c619.png)
  
 Edit: 
 just now I noticed these logs
 
![image](https://user-images.githubusercontent.com/4036085/212676135-04ab3556-03c2-473b-ad21-188bf3a3a1cf.png)
![image](https://user-images.githubusercontent.com/4036085/212676554-f62120c5-9a9d-4f89-b101-3fc10acd8b80.png)

**Comment by nathanmarlor** [comment]
Thanks.

Can you include the last two days history of 'battery soc' and 'power now' please?

**Comment by nathanmarlor** [comment]
Also, please try upgrading to 1.5.2.

**Comment by kevinverelst** [comment]
> Also, please try upgrading to 1.5.2.

I think I have the latest release 1.5.2 installed but in the file const.py, there is still a variable `VERSION = "1.5.0b1"`

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/4036085/212751491-0b741b0e-c19d-4654-a3ce-9a647923b725.png">

> Thanks.
> 
> Can you include the last two days history of 'battery soc' and 'power now' please?

Here is my "battery SoC". Keep in mind that I have been using an automation to charge starting at 00:30 untill 02:30 using the services this integration exposes.
<img width="1783" alt="image" src="https://user-images.githubusercontent.com/4036085/212751682-5e80055f-71fd-421a-8ab3-f5069df8acd5.png">

Here is my "current power usage"
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/4036085/212752159-4b56fdd8-868b-4390-82e7-e82ab7eec763.png">

As you can see, the charging of the battery and my current usage align pretty good, as one would expect.

**Comment by nathanmarlor** [comment]
Ah, gotcha - must have forgotten to update the const :)

I think you may be using the wrong entity for house load - it's intended to be the power draw of the house rather than what appears to be grid consumption (?) If you're using the modbus integration it's the entity named load_power (iirc).

![Screenshot_20230116-202816.png](https://user-images.githubusercontent.com/3436911/212760810-4130a187-131e-4c8b-81c4-31cde4a597f0.png)

**Comment by kevinverelst** [comment]
Aha, it is indeed the grid consumption now. 
I'm afraid I don't have the load power entity because of [this modbus](https://github.com/rsaemann/HA-FoxESS-H3-Modbus) fork I needed to use to get it working with my H3-5.0-E inverter. 
I'm afraid that I don't know which address I could use from the 3-phase inverter [modbus docs](https://github.com/rsaemann/HA-FoxESS-H3-Modbus/wiki/H3-Modbus-Registers)

**Comment by kevinverelst** [comment]
Maybe I could use these 3 combined and calculated in kW?
<img width="720" alt="image" src="https://user-images.githubusercontent.com/4036085/212765225-951e6e90-0357-4c7e-8531-e70b39566848.png">

**Comment by kevinverelst** [comment]
mmh, that seems to be only 11W. That isn't right

**Comment by nathanmarlor** [comment]
Not overly familiar with 3-phase systems so may be worth sticking a post on the modbus GitHub and seeing what others are doing to grab the house load?

**Comment by kevinverelst** [comment]
I'll close this issue since it seems there is nothing wrong with it but I just used the wrong data. Thx for the help.

**Comment by nathanmarlor** [comment]
Thanks, give me a shout if you're still having trouble once you get the data sorted ☺️
