### ISSUE TITLE
Using grid power after overnight charge 

### ISSUE THREAD

**Issue by andykorol1** [nathanmarlor/foxess_em#152]
Hi, the last 2 mornings I've got up and the battery has charged as normal but it is staying on grid use. Both mornings I've gone to the foxess app and the attached screenshot were the settings. I've never put these in before. As soon as I correct them it all works again. Cheers 
![Screenshot_20230122-074859](https://user-images.githubusercontent.com/111964964/213906892-d07b07d2-9de4-4349-b562-d22888fe6c09.png)

**Comment by nathanmarlor** [comment]
Thanks Andy. Can you attach some logs from around the time it should've stopped charging please? I'm guessing at a Fox Cloud connectivity issue.

**Comment by andykorol1** [comment]
![foxess fault](https://user-images.githubusercontent.com/111964964/213908429-e4e7bb98-3bfe-4b2b-934f-2456667906b2.jpg)

**Comment by andykorol1** [comment]
`Logger: homeassistant
Source: helpers/event.py:336
First occurred: 6:30:00 AM (1 occurrences)
Last logged: 6:30:00 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/foxess_em/charge/charge_service.py", line 140, in _eco_end
    self._stop_listening()
  File "/config/custom_components/foxess_em/charge/charge_service.py", line 171, in _stop_listening
    listener()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 308, in remove_listener
    _async_remove_indexed_listeners(
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 336, in _async_remove_indexed_listeners
    callbacks[storage_key].remove(job)
ValueError: list.remove(x): x not in list
`

**Comment by andykorol1** [comment]
The last one is the at 6.30am when it should stop charging

**Comment by nathanmarlor** [comment]
Not quite as I thought then. Can you confirm what version you're on please?

**Comment by andykorol1** [comment]
Foxess energy management
1.5.2 

Inverter
Master 1.48
Slave 1.02
Manager 1.45

**Comment by nathanmarlor** [comment]
Thanks. Does it continue to do this after a restart of HA? Has it happened all of a sudden? 

In short once the charging has finished we remove the listener to battery SoC (used to turn off charging when the desired SoC has been met) to prevent being notified about any other changes. It seems that HA/this component has lost the reference to that listener, which is very odd.

**Comment by nathanmarlor** [comment]
Also, are there any errors around the off peak start time?

**Comment by andykorol1** [comment]
Hi, It started randomly with no changes to HA but this morning appears to have sorted itself out. Didn't update anything so I'm guessing it got itself in a twist. Something I have noticed is the Capacity:next dawn time is 02:30 when my cheap window starts not actual daytime dawn. Is this correct? Also cheers for all the hard work that has gone into this.

**Comment by nathanmarlor** [comment]
Thanks! It'll be much more useful in spring time when we start to see some proper solar!

Can you send me a screenshot of all the params please (like the attached)? Also a screenshot of the last 24h of house load. Dawn time should be the first time in the day that predicted solar is greater than predicted house load (or 12:00 midday if it doesn't exceed).

![Screenshot_20230123-194454.png](https://user-images.githubusercontent.com/3436911/214134745-4e1897f7-a011-4568-b356-913d5fda065d.png)

![Screenshot_20230123-194503.png](https://user-images.githubusercontent.com/3436911/214134776-2bee9cdd-db81-4915-9e0e-4cfe5f61d26d.png)

**Comment by andykorol1** [comment]
![dawn](https://user-images.githubusercontent.com/111964964/214136064-5f31b66e-7f48-460c-a762-9d30d3d5fb29.jpg)
![sensors](https://user-images.githubusercontent.com/111964964/214136075-374a94b2-5aef-42c7-b60b-7cd277c1695c.jpg)
![load](https://user-images.githubusercontent.com/111964964/214136096-4182e2bd-7b08-47a3-add1-eb7ae5056dc1.jpg)

**Comment by nathanmarlor** [comment]
Odd. Have you set the timezone in HA? Container or HASS? 

What does the energy dashboard look like if you add Foxess as the solar prediction?

![Screenshot_20230123-200409.png](https://user-images.githubusercontent.com/3436911/214138528-b9ef1a48-4e81-4278-8bd5-3635ca483e1e.png)

**Comment by andykorol1** [comment]
![original](https://user-images.githubusercontent.com/111964964/214139656-e3139fa5-b001-4140-8fc4-9212bd238d4b.jpg)
![solar fox](https://user-images.githubusercontent.com/111964964/214139687-7259062a-b88d-4e85-a7c2-d4decaee70ff.jpg)

It was setup without solar prediction. Have I done the correct settings in the other photo?

**Comment by nathanmarlor** [comment]
Yep perfect, what does the energy graph look like with those inputs?

**Comment by andykorol1** [comment]
![solar new](https://user-images.githubusercontent.com/111964964/214141880-a02412a6-2442-4289-9f1e-e557b6c0c28a.jpg)

**Comment by nathanmarlor** [comment]
Now I'm super confused :)

I'm guessing the overnight load is an EV charger? Are you selecting to remove that through the Fox EM setup? I think it may be turning the load negative which then makes the diff > 0 (diff between load and solar) and confuses the calculation. I can add some extra guards around this (i.e. load is > 0) in the next release and see if it improves things for you.

**Comment by andykorol1** [comment]
Yes it is an EV charger, which I've told Fox EM to ignore.

**Comment by nathanmarlor** [comment]
@andykorol1 can you try the latest release please? Hoping this fixes your dawn calculations...

https://github.com/nathanmarlor/foxess_em/releases/tag/v1.6.0b2

**Comment by andykorol1** [comment]
![Screenshot_20230124-161624](https://user-images.githubusercontent.com/111964964/214347769-4516c2b7-d94c-4e2e-9d36-80232c1508e7.png)

Looks like it's giving me a better time to dawn now

**Comment by nathanmarlor** [comment]
Excellent! Will close this issue down.

BTW - the two capacity (dawn/eco end) entities can be deleted now, they were removed a few versions ago.
