### ISSUE TITLE
Corroborate Documentation

### ISSUE THREAD

**Issue by Ndrinta** [nathanmarlor/foxess_em#187]
Hi Nathan,

I was going through the Configuration process again and I noticed that in the Battery Config tab there are 2 new parameter not detailed in the documentation. I think those are related to v1.6.1 > changes > features > 1, 2 and 3.
I believe it's worthwhile explain these new parameters a little more.

What is the "Battery Volts (V)" parameter and when we should change it?
What is the "Charge Rate (A)" and when is applied?
What is the "custom charge profile" and how does it work?

**Comment by nathanmarlor** [comment]
Updated, thanks!
