### ISSUE TITLE
Could not make request to Fox Cloud - Error: 40257

### ISSUE THREAD

**Issue by SteveBrailsord** [nathanmarlor/foxess_em#203]
Hi 
I'm using Modbus configuration - not cloud service and getting the below error in logs 
Should I  have deleted something out of config so I dont get this error ?
I cant see that it has any negative effects though ?

## Describe the bug

Logger: custom_components.foxess_em.fox.fox_cloud_service
Source: custom_components/foxess_em/fox/fox_cloud_service.py:129
Integration: FoxESS - Energy Management ([documentation](https://github.com/nathanmarlor/foxess_em), [issues](https://github.com/nathanmarlor/foxess_em/issues))
First occurred: 00:25:20 (2 occurrences)
Last logged: 04:30:41

Could not make request to Fox Cloud - Error: 40257

## Debug log

```text

Add your logs here.

```

**Comment by nathanmarlor** [comment]
This is an invalid request to Fox - likely that the custom charge profile isn't working due to a fw mis-match. It can be ignored and it's fixed in the latest beta.
