### ISSUE TITLE
Battery Actual showing too high

### ISSUE THREAD

**Issue by djdarlo** [nathanmarlor/foxess_em#206]
My battery got to 100% today which should be 2x2.88kwh but it was showing 9.2kwh on the chart. 

I've attached a few screenshots of the graph and settings to see if I'm doing anything wrong. ![image](https://user-images.githubusercontent.com/20640104/223827139-944854c7-0f1d-46eb-b30f-d4d300099bfd.png)

**Comment by djdarlo** [comment]
![image](https://user-images.githubusercontent.com/20640104/223827305-d80e21c6-be8d-41bc-b77d-7c23c7489b8e.png)

**Comment by nathanmarlor** [comment]
There's a hardcoded battery capacity variable within the apex charts yaml :)

**Comment by djdarlo** [comment]
Doh!!!!!
