### ISSUE TITLE
Support for aggregating multiple forecasts

### ISSUE THREAD

**Issue by lis0r** [nathanmarlor/foxess_em#209]
Hi,

I have two strings of panels, one facing South, one facing West. It seems like Solcast doesn't support handling these as one site, so I've set up two sites. It would be nice if this plugin could get the forecast for both sites and add them together, please.

Thanks!

**Comment by nathanmarlor** [comment]
@lis0r it should already pickup both - if you check the logs it will show refreshing for two sites. What's shown which makes you believe it isn't?

**Comment by nathanmarlor** [comment]
Btw this was done under https://github.com/nathanmarlor/foxess_em/pull/69
