### ISSUE TITLE
Multiple Solcast sites

### ISSUE THREAD

**Issue by nathanmarlor** [nathanmarlor/foxess_em#24]
### Discussed in https://github.com/nathanmarlor/foxess_em/discussions/20

<div type='discussions-op-text'>

<sup>Originally posted by **DanL78** October 19, 2022</sup>
Is it possible to add more than one site from solcast?

Due to the way solcast records a site you can only enter one side of a pitched roof per site, so having solar panels on both side of your roof (ie, west facing side of the roof and east facing side roof) have to be entered as seperate sites to get accurate data.

Unfortunately this means we can only record half the projected solar generation, ideally we'd need to add two sites and add the generation together to create one forecast. - if possible.

Thanks in advance</div>

**Comment by Captain0Kangaroo** [comment]
its possible using this code in your configuration.ymal

# Solcast configuration to join two arrays:
  - platform: template
    sensors:
      solcast_forecast_total:
        friendly_name: "Solcast Forecast - Total"
        value_template: "{{ states('sensor.solcast_back_array') | float + states('sensor.solcast_front_array') | float }}"
        unit_of_measurement: "kWh"
        unique_id: "FpE8m3GmgBsQ"

Just replace the sensors for whatever yours are called.

Then add this to your dashboard to check its working:
`#Add to Dashboard
type: sensor
entity: sensor.solcast_forecast_total
graph: line`

**Comment by Captain0Kangaroo** [comment]
Its possible using this code in your configuration.ymal

# Solcast configuration to join two arrays:
  - platform: template
    sensors:
      solcast_forecast_total:
        friendly_name: "Solcast Forecast - Total"
        value_template: "{{ states('sensor.solcast_back_array') | float + states('sensor.solcast_front_array') | float }}"
        unit_of_measurement: "kWh"
        unique_id: "FpE8m3GmgBsQ"

Just replace the sensors for whatever yours are called.

Then add this to your dashboard to check its working:

#Add to Dashboard
type: sensor
entity: sensor.solcast_forecast_total
graph: line
