### ISSUE TITLE
HA Log Warning: "fox_modbus.py:89"

### ISSUE THREAD

**Issue by smoketabs** [nathanmarlor/foxess_em#301]
Hi.

Just wanted to drop you a note about a few errors I've been getting since 2023.6 and your updates.

Here's a copy from my HA log - hope it can be of use?

Thanks.:

This error originated from a custom integration.

Logger: custom_components.foxess_em.fox.fox_modbus
Source: custom_components/foxess_em/fox/fox_modbus.py:89
Integration: FoxESS - Energy Management (documentation, issues)
First occurred: 17:08:50 (1 occurrences)
Last logged: 17:08:50

Error writing holding register - retry (1/5): Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 4 bytes (0 received)

**Comment by nathanmarlor** [comment]
This seems like a fairly standard error to have occurred - your modbus adapter hasn't replied with a sensible response so the integration is retrying. Feel free to re-open this if you notice this impacting functionality, or you hit 5/5 retries.
