### ISSUE TITLE
Pre-commits conflict with each other

### ISSUE THREAD

**Issue by danelphick** [nathanmarlor/foxess_em#359]
The formatters `black` and `reorder-python-imports` conflict with each other, which means the pre-commits always fail. This is because black inserts a new line between the docstring at the top and reorder-python-imports removes it. See https://github.com/psf/black/issues/4175 for details.

There doesn't appear to be a workaround using these two tools, but one suggestion is to change from `reorder-python-imports` to `isort` which has black-compatibility as a goal. It would cause a bunch of churn as they have different sort policies, but the current files need sorting anyway according to `reorder-python-imports`. If you're interested, I'll go ahead and create a PR.

**Comment by nathanmarlor** [comment]
@danelphick I haven't had much time at all to spend on EM of late, so appreciate whatever you can do to keep it up to date :)
